# Generated by Django 3.1.1 on 2021-01-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='SOME STRING', max_length=50)),
                ('category_desc', models.CharField(default='SOME STRING', max_length=500)),
                ('category_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='polls.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.category'),
        ),
    ]
